### ISSUE TITLE
Determining source for any icon usage

### ISSUE THREAD

**Issue by NickSchenck** [NickSchenck/Book-Nook#18]
As a developer 
I want a consistent source for any icons I will use
So that I can customize and personalize my page

**Comment by KristyNerhaugen** [comment]
Open Iconic has a book icon and a bookmark icon we can use: https://useiconic.com/open

**Comment by KristyNerhaugen** [comment]
There are a ton of book icons for free here as well: https://www.flaticon.com/search?word=book We just need to decide which one we want to go with

**Comment by KristyNerhaugen** [comment]
Materialize has built in icons here: https://materializecss.com/icons.html
